name = "Expronicon"
uuid = "6b7a57c9-7cc1-4fdf-b7f5-e857abae3636"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
Crayons = "4.0"
MLStyle = "0.4"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
