name = "Expronicon"
uuid = "6b7a57c9-7cc1-4fdf-b7f5-e857abae3636"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.7.1"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
MLStyle = "0.4"
TOML = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "Aqua"]
